spring:
  application:
    name: ai-code-mother-backend
    # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.56.116.176:3306/ai_code_mother
    username: root
    password: 2116472Aa!
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.qmruan.aicodemother.controller