spring:
  profiles:
    active: local
  application:
    name: ai-code-mother-backend
    # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ai_code_mother
    username: root
    password: 123456
    hikari:
      max-lifetime: 30000
      minimum-idle: 3
      maximum-pool-size: 10
      connection-test-query: SELECT 1
# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.qmruan.aicodemother.controller